### PR TITLE
fixes: [DF-322] event search

### LINKED ISSUE #578: [DF-322] event search
Implement a search bar in the events page. This should allow you to search events by:

* event name (or page/screen)
* event type
* message id

Selecting an individual event should bring up a sidebar showing the event in greater detail.

Should be featured on the `/dashboard/events` page.

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-322](https://linear.app/dittofeed/issue/DF-322/event-search)</sub>

### PR DESCRIPTION
**Pull request by Rutik7066**
/attempt #578
/fixes #578
/claim #578

This PR implements the Event Search feature as discussed in the issue.
 

https://github.com/dittofeed/dittofeed/assets/58112334/0e80c1c6-cec7-4971-a439-59ee9dc1d6f5

### CODE REVIEW

**Comment by maxgurewitz** [comment]
I think there's been a miscommunication about the purpose of this ticket, which requires making backend changes! The event search will make queries against clickhouse.

**Comment by Rutik7066** [comment]
No problem @maxgurewitz. I'll make changes.

File: packages/dashboard/src/components/eventDetailsSidebar.tsx [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+    event: string;
+    userId: string | null;
+    anonymousId: string | null;
+    processingTime: string;
+    eventTime: string;
+    traits: string;
+  } | null;
+}
+
+const EventDetailsSidebar: React.FC<EventDetailsSidebarProps> = ({
```
Comment (maxgurewitz) [inline packages/dashboard/src/components/eventDetailsSidebar.tsx:20]: This needs more styling!

Can you use a codemirror codeblock to display the traits, and monospace typogography blocks to display the remaining values?

File: packages/backend-lib/src/userEvents.ts [hunk 2]
```diff
@@ -136,6 +137,7 @@ export async function findManyEvents({
   // unix timestamp units ms
   startDate?: number;
   endDate?: number;
+  searchTerm?: string;
```
Comment (maxgurewitz) [inline packages/backend-lib/src/userEvents.ts:140]: Doing local testing, it doesn't seem that a `searchTerm` value is being passed here when I type into the search bar.

File: packages/dashboard/src/components/eventsTable.tsx [hunk 3]
```diff
@@ -173,62 +254,146 @@ export function EventsTable({
...
+    page,
+    pageSize,
+    workspaceId,
+    userId,
+    updateTotalRowCount,
+    updateEvents,
+    apiBase,
+  }: HandleChanges) => {
+    const text = (event.target as HTMLInputElement).value;
+    console.log(text);
```
Comment (maxgurewitz) [inline packages/dashboard/src/components/eventsTable.tsx:272]: Delete this.

File: packages/dashboard/src/components/eventsTable.tsx [hunk 4]
```diff
@@ -173,62 +254,146 @@ export function EventsTable({
...
+    setSearchTerm(text);
+    updateEventsPaginationRequest({
```
Comment (maxgurewitz) [inline packages/dashboard/src/components/eventsTable.tsx:274]: We probably want to debounce requests.

File: packages/dashboard/src/components/eventsTable.tsx [hunk 5]
```diff
@@ -173,62 +254,146 @@ export function EventsTable({
...
+    <>
+      <DataGrid
+        rows={sortedEvents}
+        sx={{
+          border: 2,
+          borderColor: theme.palette.grey[200],
+        }}
+        slots={{
+          toolbar: ({ onChange, value }) => (
+            <TextField
```
Comment (maxgurewitz) [inline packages/dashboard/src/components/eventsTable.tsx:348]: Can you add some padding around this?

**Review by maxgurewitz — CHANGES_REQUESTED** [review]

File: packages/dashboard/src/components/eventDetailsSidebar.tsx (hunk 1 above)
Comment (Rutik7066) [reply packages/dashboard/src/components/eventDetailsSidebar.tsx:20]: Traits is a json object with like email and other details. Do you want me to use codemirror to show json object?

Comment (Rutik7066) [reply packages/dashboard/src/components/eventDetailsSidebar.tsx:21]: 3000-rutik3-dittofeed-b0l07s2gxv6 ws-us107 gitpod io_dashboard_events

File: packages/dashboard/src/components/eventsTable.tsx [hunk 6]
```diff
@@ -85,7 +124,8 @@ export function EventsTable({
   const { page, pageSize } = paginationModel;
   const theme = useTheme();
   const workspace = useAppStore((store) => store.workspace);
-  const apiBase = useAppStore((store) => store.apiBase);
+  const apiBase ='https://3001-rutik3-dittofeed-b0l07s2gxv6.ws-us107.gitpod.io';
```
Comment (maxgurewitz) [inline packages/dashboard/src/components/eventsTable.tsx:127]: Hi Rutik can you remove this? You can override this value with the environment variable `DASHBOARD_API_BASE`

**Review by maxgurewitz — CHANGES_REQUESTED** [review]

File: packages/dashboard/src/components/eventDetailsSidebar.tsx [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+                {`${key}: ${selectedEvent[key as keyof SelectedEvent]}`}
+              </Typography>
+            ) : (
+              <></>
+            );
+          })}
+
+        {selectedEvent && selectedEvent.traits && (
+          <>
+            <Typography fontFamily={"monospace"}>Traits:</Typography>
```
Comment (maxgurewitz) [inline packages/dashboard/src/components/eventDetailsSidebar.tsx:50]: Can you use react code mirror, as demonstrated in `packages/dashboard/src/components/templateEditor.tsx` to render this json?

File: packages/dashboard/src/components/eventDetailsSidebar.tsx [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+}) => {
+  return (
+    <Drawer
+      open={open}
+      onClose={onClose}
+      anchor="right"
+      slotProps={{ backdrop: { onClick: onClose } }}
+    >
+      <Box padding={2} paddingTop={10}>
+        <Typography fontFamily={"monospace"} variant="h2">
```
Comment (maxgurewitz) [inline packages/dashboard/src/components/eventDetailsSidebar.tsx:34]: Can you use the `SubtleHeader` component here?

**Review by maxgurewitz — CHANGES_REQUESTED** [review]
Few more changes requested

File: packages/dashboard/src/components/eventDetailsSidebar.tsx (hunk 8 above)
Comment (Rutik7066) [reply packages/dashboard/src/components/eventDetailsSidebar.tsx:34]: Using SubtleHeader will not allow the font family to be monospace so I used the code instead.

Comment (maxgurewitz) [reply packages/dashboard/src/components/eventDetailsSidebar.tsx]: In the case of the header, I don't need it to be monospace!

File: packages/dashboard/src/components/eventDetailsSidebar.tsx (hunk 7 above)
Comment (maxgurewitz) [reply packages/dashboard/src/components/eventDetailsSidebar.tsx]: As discussed in chat

> the purpose of codemirror is that it just provides a better presentation. You can use codemirror in a view only mode, so that the contained code (json in this case) is static and not editable.

File: packages/dashboard/src/components/eventDetailsSidebar.tsx [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+          })}
+
+        {selectedEvent && selectedEvent.traits && (
+          <>
+            <InfoTooltip title={"Traits"}>
+              <Typography variant="h5">Traits</Typography>
+            </InfoTooltip>
+            <ReactCodeMirror
+              value={selectedEvent.traits}
+              // onChange={(json) =>
```
Comment (maxgurewitz) [inline packages/dashboard/src/components/eventDetailsSidebar.tsx:62]: Delete this

**Review by maxgurewitz — CHANGES_REQUESTED** [review]

**Comment by Rutik7066** [comment]
Hi @maxgurewitz  updated the changes.

**Review by maxgurewitz — CHANGES_REQUESTED** [review]
We need to fix the merge conflicts and lint errors!

**Comment by Rutik7066** [comment]
Hi @maxgurewitz done.

**Review by maxgurewitz — CHANGES_REQUESTED** [review]
Can you fix linting by running `yarn workspace dashboard lint --fix` and `yarn workspace backend-lib lint --fix`.

**Review by maxgurewitz — CHANGES_REQUESTED** [review]
Hey! Two issues:
1.

I'm getting this error in the console,

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `EventDetailsSidebar`. See https://reactjs.org/link/warning-keys for more information.
```

2. search no longer seems to be working

https://www.loom.com/share/301ac213ee7d44d0b0d66f30d4e6668c

**Review by maxgurewitz — CHANGES_REQUESTED** [review]
Linting errors still failing! Run the `--fix` commands again.

**Comment by maxgurewitz** [comment]
I did more testing, and search doesn't seem to be working as intended either!

**Comment by Rutik7066** [comment]
https://github.com/dittofeed/dittofeed/assets/58112334/4e2416ae-94d4-403a-841c-ce5a5c89cc24

Hi @maxgurewitz  Fixed all the issues.

**Comment by maxgurewitz** [comment]
Hi @Rutik7066
> please show a video with searching working with message id, event name, and event type

**Comment by Rutik7066** [comment]
Hi, @maxgurewitz updated the commit with the demo video. please take a look at it .

**Review by maxgurewitz — APPROVED** [review]
I'll note that we do need to update the `findEventsCount` to get the correct event count for this table (accounting for the search term), but that's not a huge issue and can be corrected later. Congrats!
